// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from 'libs/stimulus'


import AutosaveController from 'controllers/autosave_controller'
Stimulus.register('autosave', AutosaveController)

import Bridge__FormController from 'controllers/bridge/form_controller'
Stimulus.register('bridge--form', Bridge__FormController)

import Bridge__ToastController from 'controllers/bridge/toast_controller'
Stimulus.register('bridge--toast', Bridge__ToastController)

import DeleteToggleController from 'controllers/delete_toggle_controller'
Stimulus.register('delete-toggle', DeleteToggleController)

import FlashController from 'controllers/flash_controller'
Stimulus.register('flash', FlashController)

import HelloController from 'controllers/hello_controller'
Stimulus.register('hello', HelloController)

import InlineEditController from 'controllers/inline_edit_controller'
Stimulus.register('inline-edit', InlineEditController)

import KeyboardShortcutsController from 'controllers/keyboard_shortcuts_controller'
Stimulus.register('keyboard-shortcuts', KeyboardShortcutsController)

import MobileMenuController from 'controllers/mobile_menu_controller'
Stimulus.register('mobile-menu', MobileMenuController)

import PasswordRevealController from 'controllers/password_reveal_controller'
Stimulus.register('password-reveal', PasswordRevealController)

import ProjectPrefillController from 'controllers/project_prefill_controller'
Stimulus.register('project-prefill', ProjectPrefillController)

import SearchClientsController from 'controllers/search_clients_controller'
Stimulus.register('search-clients', SearchClientsController)

import SearchProjectsController from 'controllers/search_projects_controller'
Stimulus.register('search-projects', SearchProjectsController)

import SidebarController from 'controllers/sidebar_controller'
Stimulus.register('sidebar', SidebarController)

import TimerController from 'controllers/timer_controller'
Stimulus.register('timer', TimerController)

import TurboLoadingController from 'controllers/turbo_loading_controller'
Stimulus.register('turbo-loading', TurboLoadingController)